import {useEffect,useMemo,useState}from"react";
type Language="th"|"en";type Event={id:string;starts_at:string;war_type:string;status:string};type Registration={player_id:string;character_name:string;preferred_role:string|null;loadouts:{role:string}[]};type Squad="ATTACK_1"|"ATTACK_2"|"ATTACK_3"|"DEFENSE_1"|"DEFENSE_2"|"FOREST"|"STANDBY";type Organizer={displayName:string}|null;
const squads:Squad[]=["ATTACK_1","ATTACK_2","ATTACK_3","DEFENSE_1","DEFENSE_2","FOREST","STANDBY"];const labels:Record<Squad,string>={ATTACK_1:"Attack 1",ATTACK_2:"Attack 2",ATTACK_3:"Attack 3",DEFENSE_1:"Defense 1",DEFENSE_2:"Defense 2",FOREST:"Forest",STANDBY:"Standby"};const gameId="where-winds-meet";const key=(id:string)=>"pom-team-draft:"+id;
export function GuildWarTeamBuilder({language}:{language:Language}){const[events,setEvents]=useState<Event[]>([]),[eventId,setEventId]=useState(""),[roster,setRoster]=useState<Registration[]>([]),[assign,setAssign]=useState<Record<string,Squad>>({}),[organizer,setOrganizer]=useState<Organizer>(null),[search,setSearch]=useState("");
useEffect(()=>{fetch("/api/auth/discord/session").then(r=>r.json()).then(d=>setOrganizer(d.organizer||null)).catch(()=>{})},[]);
useEffect(()=>{fetch(`/api/v2/games/${gameId}/war/events`).then(r=>r.json()).then(d=>{const a=(d.events||[]).filter((x:Event)=>x.status==="open");setEvents(a);setEventId(a[0]?.id||"")})},[]);
useEffect(()=>{if(!eventId)return;fetch(`/api/v2/games/${gameId}/war/events/${eventId}/registrations`).then(r=>r.json()).then(d=>{const a=d.registrations||[];setRoster(a);let saved={};try{saved=JSON.parse(localStorage.getItem(key(eventId))||"{}")}catch{}setAssign(Object.fromEntries(a.map((p:Registration)=>[p.player_id,(saved as Record<string,Squad>)[p.player_id]||"STANDBY"])))}).catch(()=>setRoster([]))},[eventId]);
useEffect(()=>{if(organizer&&eventId)localStorage.setItem(key(eventId),JSON.stringify(assign))},[assign,eventId,organizer]);
const unassigned=useMemo(()=>roster.filter(p=>assign[p.player_id]==="STANDBY"&&p.character_name.toLowerCase().includes(search.toLowerCase())),[roster,assign,search]);const login=`/api/auth/discord/login?return=${encodeURIComponent("/games/where-winds-meet/guild-war/teams")}`;const move=(id:string,s:Squad)=>setAssign(v=>({...v,[id]:s}));
const player=(p:Registration)=><article className="team-player" key={p.player_id}><strong>{p.character_name}</strong><small>{p.preferred_role||p.loadouts[0]?.role||"—"}</small>{organizer&&<select value={assign[p.player_id]} onChange={e=>move(p.player_id,e.target.value as Squad)}>{squads.map(s=><option value={s} key={s}>{labels[s]}</option>)}</select>}</article>;
return <section className="legacy-builder"><header className="legacy-head"><div><p className="eyebrow">PATH OF MEMORIES</p><h1>{language==="th"?"จัดทีม Guild War":"Guild War Team Builder"}</h1><p>{language==="th"?"จัดทีมตามรูปแบบเดิม · ระบบทดสอบ":"Legacy workflow · test system"}</p></div>{organizer?<b>{language==="th"?`ผู้จัดทีม: ${organizer.displayName}`:`Organizer: ${organizer.displayName}`}</b>:<a className="button-primary" href={login}>{language==="th"?"เข้าสู่ระบบ Discord":"Continue with Discord"}</a>}</header>
<div className="legacy-toolbar"><select value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option value={e.id} key={e.id}>{new Date(e.starts_at).toLocaleString(language==="th"?"th-TH":"en-GB")} · {e.war_type}</option>)}</select><span>{roster.length} Registered</span><span>{roster.filter(p=>assign[p.player_id]!=="STANDBY").length} Assigned</span><span>{unassigned.length} Unassigned</span></div>
<div className="legacy-layout"><aside className="legacy-pool"><h2>Unassigned</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={language==="th"?"ค้นหาชื่อ…":"Search player…"}/>{unassigned.map(player)}</aside><main className="legacy-board"><div className="legacy-side"><h2>{language==="th"?"ฝั่งบุก":"Attack side"}</h2><div className="legacy-squads">{squads.slice(0,3).map(s=><section key={s}><h3>{labels[s]} <b>{roster.filter(p=>assign[p.player_id]===s).length}</b></h3>{roster.filter(p=>assign[p.player_id]===s).map(player)}</section>)}</div></div><div className="legacy-side"><h2>{language==="th"?"ฝั่งกัน":"Defense side"}</h2><div className="legacy-squads">{squads.slice(3,6).map(s=><section key={s}><h3>{labels[s]} <b>{roster.filter(p=>assign[p.player_id]===s).length}</b></h3>{roster.filter(p=>assign[p.player_id]===s).map(player)}</section>)}</div></div></main></div></section>}