import {useEffect, useState} from "react";
type Language="th"|"en"; type Event={id:string;starts_at:string;war_type:string;status:string;capacity:number}; type Registration={player_id:string;character_name:string;preferred_role:string|null;note:string;loadouts:{id:string;role:string;main_weapon_name:string;sub_weapon_name:string}[]}; type Squad="Attack 1"|"Attack 2"|"Defense"|"Reserve"; type Organizer={id:string;displayName:string}|null;
const gameId="where-winds-meet"; const squads:Squad[]=["Attack 1","Attack 2","Defense","Reserve"]; const draftKey=(id:string)=>`pom-team-draft:${id}`;
function savedAssignments(id:string):Record<string,Squad>{try{const v=JSON.parse(localStorage.getItem(draftKey(id))||"{}");return Object.fromEntries(Object.entries(v).filter(([,s])=>squads.includes(s as Squad))) as Record<string,Squad>}catch{return{}}}
export function GuildWarTeamBuilder({language}:{language:Language}){
 const[events,setEvents]=useState<Event[]>([]);const[eventId,setEventId]=useState("");const[registrations,setRegistrations]=useState<Registration[]>([]);const[assignments,setAssignments]=useState<Record<string,Squad>>({});const[state,setState]=useState<"loading"|"ready"|"error">("loading");const[organizer,setOrganizer]=useState<Organizer>(null);const[authChecked,setAuthChecked]=useState(false);
 useEffect(()=>{fetch("/api/auth/discord/session").then(r=>r.ok?r.json():Promise.reject()).then(d=>setOrganizer(d.organizer||null)).catch(()=>setOrganizer(null)).finally(()=>setAuthChecked(true))},[]);
 useEffect(()=>{fetch(`/api/v2/games/${gameId}/war/events`).then(r=>r.json()).then(d=>{const open=(d.events||[]).filter((e:Event)=>e.status==="open");setEvents(open);setEventId(open[0]?.id||"");setState("ready")}).catch(()=>setState("error"))},[]);
 useEffect(()=>{if(!eventId)return;setState("loading");fetch(`/api/v2/games/${gameId}/war/events/${eventId}/registrations`).then(r=>r.json()).then(d=>{const roster=d.registrations||[],previous=savedAssignments(eventId);setRegistrations(roster);setAssignments(Object.fromEntries(roster.map((x:Registration)=>[x.player_id,previous[x.player_id]||"Reserve"])));setState("ready")}).catch(()=>setState("error"))},[eventId]);
 useEffect(()=>{if(organizer&&eventId&&state==="ready"&&registrations.length)localStorage.setItem(draftKey(eventId),JSON.stringify(assignments))},[assignments,eventId,organizer,registrations.length,state]);
 const resetDraft=()=>{localStorage.removeItem(draftKey(eventId));setAssignments(Object.fromEntries(registrations.map(x=>[x.player_id,"Reserve"])))};
 const loginUrl=`/api/auth/discord/login?return=${encodeURIComponent("/games/where-winds-meet/guild-war/teams")}`;
 return <section className="team-builder"><div className="registration-heading"><div><p className="eyebrow">ORGANIZER · TEAM BUILDER</p><h1>{language==="th"?"จัดทีมของคืนนี้":"Build tonight's teams"}</h1></div><span>{language==="th"?"DRAFT · ยังไม่ประกาศ":"DRAFT · NOT PUBLISHED"}</span></div>
 {authChecked&&!organizer&&<aside className="organizer-signin"><div><strong>{language==="th"?"สำหรับผู้จัดทีม":"For organizers"}</strong><p>{language==="th"?"เข้าสู่ระบบด้วย Discord เพื่อจัด draft":"Sign in with Discord to arrange a draft."}</p></div><a className="button-primary" href={loginUrl}>{language==="th"?"เข้าสู่ระบบด้วย Discord":"Continue with Discord"}</a></aside>}
 {organizer&&<aside className="organizer-signin organizer-active"><div><strong>{language==="th"?`ผู้จัดทีม: ${organizer.displayName}`:`Organizer: ${organizer.displayName}`}</strong><p>{language==="th"?"คุณกำลังจัด draft ส่วนตัว":"You are editing a private draft."}</p></div></aside>}
 {events.length>0&&<label className="team-event-select">{language==="th"?"เลือกรอบ War":"Choose a War round"}<select value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{new Date(e.starts_at).toLocaleString(language==="th"?"th-TH":"en-GB",{dateStyle:"medium",timeStyle:"short"})} · {e.war_type}</option>)}</select></label>}
 {state==="loading"&&<p className="team-builder-message">✦ {language==="th"?"กำลังเรียกรายชื่อ…":"Gathering the roster…"}</p>}{state==="error"&&<p className="registration-error">{language==="th"?"ยังโหลดรายชื่อไม่ได้":"The roster is unavailable."}</p>}{state==="ready"&&!events.length&&<p className="team-builder-message">{language==="th"?"ยังไม่มีรอบ War ที่เปิดอยู่":"No War round is currently open."}</p>}
 {organizer&&state==="ready"&&registrations.length>0&&<><div className="draft-actions"><span>{language==="th"?"บันทึก draft ใน browser เครื่องนี้แล้ว":"Draft is saved in this browser."}</span><button type="button" onClick={resetDraft}>{language==="th"?"เริ่มจัดใหม่":"Reset draft"}</button></div><div className="squad-grid">{squads.map(s=><section className="squad-column" key={s}><header><span>{s}</span><b>{Object.values(assignments).filter(v=>v===s).length}</b></header><div>{registrations.filter(r=>assignments[r.player_id]===s).map(r=><article className="team-player" key={r.player_id}><div><strong>{r.character_name}</strong><small>{r.preferred_role||r.loadouts[0]?.role||"—"}</small></div><select value={assignments[r.player_id]} onChange={e=>setAssignments(c=>({...c,[r.player_id]:e.target.value as Squad}))}>{squads.map(t=><option value={t} key={t}>{t}</option>)}</select></article>)}</div></section>)}</div></>}
 {state==="ready"&&eventId&&!registrations.length&&<p className="team-builder-message">{language==="th"?"ยังไม่มีผู้ลงทะเบียนในรอบนี้":"No registrations for this round yet."}</p>}{organizer&&<p className="manager-note">✦ {language==="th"?"Draft นี้อยู่ใน browser ของคุณเท่านั้น ยังไม่กระทบรายชื่อจริง":"This draft stays only in your browser and does not change the live roster."}</p>}</section>
}