import {useEffect,useRef,useState} from 'react';
import './GuildWarRegistration.css';
type Player={id:string;character_name:string;nickname?:string;loadouts:Loadout[]};
type Loadout={id:string;role:string;main_weapon_name:string;sub_weapon_name:string};
type Round={id:string;starts_at:string;local_date:string;war_type:string;status:string;round_number:number;ends_at:string};
type Weapon={id:string;name:string};
const base='/api/v2/games/where-winds-meet';
const teamNames=[['','ทีมไหนก็ได้','Any team'],['ATTACK_1','บุก 1','Attack 1'],['ATTACK_2','บุก 2','Attack 2'],['ATTACK_3','บุก 3','Attack 3'],['DEFENSE_1','กัน 1','Defense 1'],['DEFENSE_2','กัน 2','Defense 2'],['FOREST','ป่า','Forest'],['STANDBY','สำรอง','Standby']];
const weaponThai:Record<string,string>={
  'Infernal Twinblades':'ดาบคู่เพลิงนรก','Thundercry Blade':'ดาบอสนีครวญ','Inkwell Fan':'พัดหมึก','Mortal Rope Dart':'เชือกบินสังหาร','Strategic Sword':'กระบี่กลยุทธ์','Snowparting Blade':'ดาบแหวกหิมะ','Phalanxbane Blade':'ดาบทำลายทัพ','Panacea Fan':'พัดร้อยโอสถ','Vernal Umbrella':'ร่มวสันต์','Nameless Sword':'กระบี่ไร้นาม','Nameless Spear':'หอกไร้นาม','Stormbreaker Spear':'หอกทำลายพายุ','Soulshade Umbrella':'ร่มเงาวิญญาณ','Heavenquaker Spear':'หอกสั่นสวรรค์','Heavenwill Gauntlets':'สนับมือเจตจำนงสวรรค์','Skygrasp Rope Dart':'เชือกบินคว้านภา','Everspring Umbrella':'ร่มวสันต์นิรันดร์','Unfettered Rope Dart':'เชือกบินไร้พันธนาการ'
};
const weaponSets=[
  ['Nameless Sword','Nameless Spear'],['Strategic Sword','Heavenquaker Spear'],['Panacea Fan','Vernal Umbrella'],['Inkwell Fan','Soulshade Umbrella'],['Infernal Twinblades','Mortal Rope Dart'],['Thundercry Blade','Stormbreaker Spear'],['Snowparting Blade','Phalanxbane Blade'],['Heavenwill Gauntlets','Skygrasp Rope Dart'],['Everspring Umbrella','Unfettered Rope Dart']
];
const key=(id:string)=>'pom-member:'+id;
async function json(url:string,body?:unknown){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'request_failed');return d;}
function credentials(playerId:string){const claims:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(k.startsWith('pom-war-claim:')&&k.endsWith(':'+playerId))claims[k.slice(14,-playerId.length-1)]=localStorage.getItem(k)||'';}return {playerId,token:localStorage.getItem(key(playerId)),claims};}
export function GuildWarRegistration({language}:{language:'th'|'en'}) {
  const th=language==='th',t=(a:string,b:string)=>th?a:b;
  const [players,setPlayers]=useState<Player[]>([]),[events,setEvents]=useState<Round[]>([]),[weekStart,setWeek]=useState('');
  const [playerId,setPlayer]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState<string[]>([]),[regularSlots,setRegularSlots]=useState<string[]>([]),[loadoutIds,setLoadouts]=useState<string[]>([]);
  const [role,setRole]=useState(''),[team,setTeam]=useState(''),[note,setNote]=useState(''),[regular,setRegular]=useState(false),[editingRegular,setEditingRegular]=useState(false),[revision,setRevision]=useState(0);
  const [busy,setBusy]=useState(true),[loadingProfile,setLoadingProfile]=useState(false),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
  const [newPlayer,setNewPlayer]=useState(false),[name,setName]=useState(''),[nickname,setNickname]=useState('');
  const [newBuild,setNewBuild]=useState(false),[weapons,setWeapons]=useState<Weapon[]>([]),[buildRole,setBuildRole]=useState('DPS'),[main,setMain]=useState(''),[sub,setSub]=useState(''),[weaponSet,setWeaponSet]=useState(''),[customWeapons,setCustomWeapons]=useState(false);
  const generation=useRef(0),player=players.find(p=>p.id===playerId);
  const error=(e:unknown)=>{setFailed(true);const code=e instanceof Error?e.message:'';setMessage(code==='claim_required'?t('รายการนี้ถูกแก้ไขจากอีกเครื่อง กรุณาใช้เครื่องเดิมหรือติดต่อผู้จัด','Use the original device or contact an organizer to edit this member.'):code==='conflict'?t('ข้อมูลเปลี่ยนแล้ว กรุณาเลือกตัวละครใหม่เพื่อโหลดข้อมูลล่าสุด','Data changed. Select the character again to reload.'):code==='name_exists'?t('มีชื่อตัวละครนี้แล้ว กรุณาเลือกจากรายชื่อ','This character already exists. Select it from the list.'):t('บันทึกหรือโหลดข้อมูลไม่สำเร็จ กรุณาลองใหม่','Could not load or save. Please retry.'));};
  async function initialize(){setBusy(true);try{const [rounds,data]=await Promise.all([json(base+'/member-registration'),json(base+'/players')]);setEvents(rounds.events);setWeek(rounds.weekStart);setPlayers(data.players);setMessage('');setFailed(false);}catch(e){error(e);}finally{setBusy(false);}}
  useEffect(()=>{void initialize();},[]);
  useEffect(()=>{const version=++generation.current;setReady(false);setSelected([]);setRegularSlots([]);setEditingRegular(false);setLoadouts([]);setRole('');setTeam('');setNote('');setRegular(false);setMessage('');setNewBuild(false);if(!playerId)return;setLoadingProfile(true);
    json(base+'/member-registration/lookup',credentials(playerId)).then(d=>{if(version!==generation.current)return;setRevision(d.revision);setSelected(d.selected);setRegularSlots(d.regularSlots||[]);setLoadouts(d.loadoutIds);setRole(d.preferredRole);setTeam(d.preferredTeam);setRegular(d.regular);setNote(d.note);setWeapons(d.weapons);setReady(true);setFailed(false);}).catch(e=>{if(version===generation.current)error(e);}).finally(()=>{if(version===generation.current)setLoadingProfile(false);});
  },[playerId]);
  async function save(){if(!ready)return;setBusy(true);setMessage('');try{const d=await json(base+'/member-registration/save',{...credentials(playerId),weekStart,selected,regularSlots,loadoutIds,preferredRole:role,preferredTeam:team,note,regular,revision});localStorage.setItem(key(playerId),d.token);setRevision(d.revision);setEditingRegular(false);setFailed(false);setMessage(regular?t('บันทึกแล้ว รอบขาประจำและสถานะสัปดาห์นี้ได้รับการอัปเดต','Saved. Your regular rounds and this week’s availability are updated.'):t('บันทึกรอบสัปดาห์นี้แล้ว','This week’s registration is saved.'));}catch(e){error(e);}finally{setBusy(false);}}
  async function addPlayer(){setBusy(true);try{const d=await json(base+'/member-registration/player',{characterName:name,nickname});localStorage.setItem(key(d.playerId),d.token);const p=await json(base+'/players');setPlayers(p.players);setSearch('');setPlayer(d.playerId);setNewPlayer(false);setName('');setNickname('');}catch(e){error(e);}finally{setBusy(false);}}
  async function addBuild(){setBusy(true);try{const claim=await json(base+'/member-registration/claim',credentials(playerId));localStorage.setItem(key(playerId),claim.token);setRevision(claim.revision);const d=await json(base+'/member-registration/loadout',{...credentials(playerId),role:buildRole,mainWeapon:main,subWeapon:sub});const p=await json(base+'/players');setPlayers(p.players);setLoadouts(ids=>[...ids,d.id]);setRole(buildRole);setNewBuild(false);}catch(e){error(e);}finally{setBusy(false);}}
  const available=(e:Round)=>e.status==='open'&&new Date(e.starts_at)>new Date();
  const shownRounds=editingRegular?regularSlots:selected;
  function toggleRound(id:string){
    const next=shownRounds.includes(id)?shownRounds.filter(value=>value!==id):[...shownRounds,id];
    if(editingRegular){setRegularSlots(next);setSelected(next);}
    else setSelected(next);
  }
  function toggleRegular(){
    if(!regular){setRegular(true);setRegularSlots(selected);setEditingRegular(true);return;}
    setEditingRegular(value=>!value);
  }
  function chooseWeaponSet(value:string){
    setWeaponSet(value);setCustomWeapons(false);
    const pair=weaponSets[Number(value)];
    const mainWeapon=weapons.find(w=>w.name===pair?.[0]);
    const subWeapon=weapons.find(w=>w.name===pair?.[1]);
    setMain(mainWeapon?.id||'');setSub(subWeapon?.id||'');
  }
  const weaponLabel=(name:string)=>weaponThai[name]?name+' · '+weaponThai[name]:name;
  return <section className="legacy-register"><header><small>PATHOFMEMORIES</small><h1>Guild War Registration</h1><p>{t('เลือกตัวละคร รอบเวลา และ Role ที่พร้อมเล่น','Choose your character, War rounds and available roles')}</p></header>
    <fieldset disabled={busy} className="registration-body">
      <section className="registration-panel"><h2>{t('1. ตัวละครของคุณ','1. Your character')}</h2><input aria-label={t('ค้นหาตัวละคร','Search characters')} placeholder={t('ค้นหาชื่อตัวละคร / ชื่อเล่น…','Search character / nickname…')} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={t('เลือกตัวละคร','Choose character')} value={playerId} onChange={e=>setPlayer(e.target.value)}><option value="">{t('-- เลือกตัวละคร --','-- Choose character --')}</option>{players.filter(p=>p.id===playerId||(p.character_name+' '+p.nickname).toLowerCase().includes(search.toLowerCase())).map(p=><option key={p.id} value={p.id}>{p.character_name}{p.nickname?' ('+p.nickname+')':''}</option>)}</select><hr/><button type="button" onClick={()=>setNewPlayer(!newPlayer)}>+ {t('สมัคร Player ใหม่','New player')}</button>{newPlayer&&<div className="registration-inline"><label>{t('ชื่อตัวละคร','Character name')}<input value={name} maxLength={64} onChange={e=>setName(e.target.value)}/></label><label>{t('ชื่อเล่น','Nickname')}<input value={nickname} maxLength={64} onChange={e=>setNickname(e.target.value)}/></label><button type="button" disabled={!name.trim()} onClick={()=>void addPlayer()}>{t('เพิ่มตัวละคร','Create character')}</button></div>}</section>
      <fieldset disabled={!ready||loadingProfile} className="registration-body">
        <section className="registration-panel"><h2>{t('2. รอบ War ที่มาได้','2. Available War rounds')}</h2>{editingRegular&&<p className="registration-editing">★ {t('กำลังแก้ไขรอบขาประจำ: ติ๊กเฉพาะรอบที่ต้องการให้ลงอัตโนมัติทุกสัปดาห์','Editing regular rounds: select the rounds to register automatically every week.')}</p>}{[...new Set(events.map(e=>e.local_date))].map(date=><div key={date} className="registration-day"><h3>{new Date(date+'T12:00:00+07:00').toLocaleDateString(th?'th-TH':'en-GB',{timeZone:'Asia/Bangkok',weekday:'long',day:'numeric',month:'short',year:'numeric'})}</h3>{events.filter(e=>e.local_date===date).map(e=>{const isRegular=regular&&regularSlots.includes(e.id),isTemporaryAway=isRegular&&!selected.includes(e.id);return <label className={'registration-round '+(isRegular?'is-regular':'')} key={e.id}><input type="checkbox" disabled={!available(e)} checked={shownRounds.includes(e.id)} onChange={()=>toggleRound(e.id)}/><span>{t('รอบ ','Round ')}{e.round_number} · {new Date(e.starts_at).toLocaleTimeString('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'})}{e.ends_at?'–'+e.ends_at:''} <small>{e.war_type==='Matching'?'Rank':e.war_type}</small>{isRegular&&<strong className="regular-badge">★ {isTemporaryAway?t('ขาประจำ · ไม่สะดวกรอบนี้','Regular · unavailable this round'):t('ขาประจำ','Regular')}</strong>}{!available(e)&&<em>{t('ปิดรับลงทะเบียน','Closed')}</em>}</span></label>})}</div>)}{!events.length&&<p>{t('ยังไม่มีรอบที่เปิด','No rounds available')}</p>}<button type="button" className={'regular-button '+(regular?'selected':'')} aria-pressed={regular} onClick={toggleRegular}>{regular?(editingRegular?t('เสร็จสิ้นการแก้ไขขาประจำ','Done editing regular rounds'):t('แก้ไขรอบขาประจำ','Edit regular rounds')):t('★ ตั้งเป็นขาประจำจากรอบที่เลือก','★ Make selected rounds regular')}</button>{regular&&<button type="button" className="regular-disable" onClick={()=>{setRegular(false);setEditingRegular(false);setRegularSlots([]);}}>{t('ยกเลิกขาประจำทั้งหมด','Turn off regular attendee')}</button>}<p className="registration-hint">{editingRegular?t('กด “เสร็จสิ้นการแก้ไขขาประจำ” แล้วบันทึกเพื่อเปลี่ยนตารางถาวร','Click “Done editing regular rounds” then save to change the recurring schedule.'):t('รอบที่มี ★ คือขาประจำ การเอาติ๊กออกในโหมดปกติหมายถึงไม่ว่างเฉพาะสัปดาห์นี้','Rounds with ★ are regular. Unticking in normal mode means unavailable this week only.')}</p></section>
        <section className="registration-panel"><h2>{t('3. Role ที่พร้อมเล่น','3. Available roles')}</h2><p className="registration-hint">{t('เลือกได้หลาย Role และเลือก Role ที่อยากเล่นอีกครั้งด้านล่าง','Choose available builds and a preferred role below.')}</p>{player?.loadouts.map(l=><label className="registration-build" key={l.id}><input type="checkbox" checked={loadoutIds.includes(l.id)} onChange={()=>{setLoadouts(ids=>ids.includes(l.id)?ids.filter(id=>id!==l.id):[...ids,l.id]);setRole('');}}/><span><b>{l.role}</b> · {weaponLabel(l.main_weapon_name)} + {weaponLabel(l.sub_weapon_name)}</span></label>)}<label>{t('Role ที่อยากเล่น','Preferred role')}<select value={role} onChange={e=>setRole(e.target.value)}><option value="">{t('-- เลือก Role --','-- Choose role --')}</option>{[...new Set(player?.loadouts.filter(l=>loadoutIds.includes(l.id)).map(l=>l.role))].map(r=><option key={r}>{r}</option>)}</select></label><hr/><button type="button" onClick={()=>{setNewBuild(!newBuild);setCustomWeapons(false);setWeaponSet('');setMain('');setSub('');}}>+ {t('เพิ่ม Loadout ใหม่','New loadout')}</button>{newBuild&&<div className="registration-inline"><label>Role<select value={buildRole} onChange={e=>setBuildRole(e.target.value)}>{['DPS','Tank','Heal'].map(r=><option key={r}>{r}</option>)}</select></label><label>{t('Weapon Set พื้นฐาน','Standard Weapon Set')}<select aria-label={t('Weapon Set พื้นฐาน','Standard Weapon Set')} value={weaponSet} onChange={e=>chooseWeaponSet(e.target.value)}><option value="">{t('-- เลือก Weapon Set --','-- Choose a Weapon Set --')}</option>{weaponSets.map((pair,index)=>pair.every(name=>weapons.some(w=>w.name===name))&&<option key={pair.join('/')} value={String(index)}>{weaponLabel(pair[0])} + {weaponLabel(pair[1])}</option>)}</select></label>{weaponSet&&!customWeapons&&<p className="registration-hint">{t('ชุดพื้นฐานจากเกม Where Winds Meet','Standard Where Winds Meet weapon set')}</p>}<button type="button" className={customWeapons?'selected':''} onClick={()=>{setCustomWeapons(true);setWeaponSet('');setMain('');setSub('');}}>{t('Custom / สายผสม','Custom / mixed build')}</button>{customWeapons&&<div className="registration-custom"><p className="registration-hint">{t('เลือกอาวุธเองสำหรับสายผสม','Choose each weapon for a mixed build.')}</p>{(['main','sub'] as const).map(kind=><label key={kind}>{kind==='main'?'Main Weapon':'Sub Weapon'}<select value={kind==='main'?main:sub} onChange={e=>kind==='main'?setMain(e.target.value):setSub(e.target.value)}><option value="">—</option>{weapons.map(w=><option key={w.id} value={w.id}>{weaponLabel(w.name)}</option>)}</select></label>)}</div>}<button disabled={!main||!sub||main===sub} type="button" onClick={()=>void addBuild()}>{t('บันทึก Loadout','Save loadout')}</button></div>}</section>
        <section className="registration-panel"><h2>{t('4. ทีมที่อยากเล่น','4. Preferred team')}</h2><select aria-label={t('ทีมที่อยากเล่น','Preferred team')} value={team} onChange={e=>setTeam(e.target.value)}>{teamNames.map(([id,thai,en])=><option key={id} value={id}>{th?thai:en}</option>)}</select><label>{t('หมายเหตุถึงคนจัดทีม','Note for the organizer')}<textarea value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder={t('เช่น อาจมาช้า อยากอยู่ทีมเดียวกัน…','For example: may arrive late…')}/></label></section>
        <button className="registration-save" type="button" onClick={()=>void save()}>{t('บันทึกการลงทะเบียน','Save registration')}</button><p className="registration-hint">{t('รอบที่ไม่ติ๊กจะถือว่าไม่มาในสัปดาห์นี้ หากถอนทุกรอบให้เอาติ๊กออกทั้งหมดแล้วบันทึก','Unchecked rounds mean unavailable this week. Uncheck all rounds and save to withdraw for the week.')}</p>
      </fieldset>
    </fieldset>
    {busy||loadingProfile?<p role="status">{t('กำลังโหลดหรือบันทึก…','Loading or saving…')}</p>:null}
    {message&&<p role={failed?'alert':'status'} className={failed?'registration-error':'registration-success'}>{message}</p>}
    {failed&&!events.length&&<button type="button" onClick={()=>void initialize()}>{t('ลองใหม่','Retry')}</button>}
  </section>;
}
